version: '3'
services: 
  db:
    image: mysql:8
    ports:
      - 3306:3306
    environment: 
      MYSQL_ROOT_PASSWORD: shigure
      MYSQL_DATABASE: shigure
      MYSQL_USER: shigure
      MYSQL_PASSWORD: shigure
    volumes:
      - ./mysql_data:/var/lib/mysql